<div style="text-align:center">
    <h1>Numpy. 📈</h1>
</div>

<div style="text-align:center">
    <img src="Datas/numpy.png" width="500rem" />
</di>

### 🈳 Numpy é usado para computação numérica e manipulação de arrays multidimensionais.

In [1]:
# !pip install numpy

In [2]:
import numpy as np # DOC: https://numpy.org/doc/stable/user/absolute_beginners.html

In [3]:
# Array sao formados por linhas e colunas, logo array de (3, 2): 

np.array([[1,5], [4,7], [7,2]])

array([[1, 5],
       [4, 7],
       [7, 2]])

In [4]:
# Array de 1D

np.array([1,5,6])

array([1, 5, 6])

In [5]:
# Array de 2D

np.array([[1,5,6], [5,8,2]])

array([[1, 5, 6],
       [5, 8, 2]])

#### 💎 Encontrar valores mínimos, máximos e medianos em um array:

In [172]:
array = np.random.randint(8, 80, size=[3,3])

print(f"Valor minimo: {array.min()}")
print(f"Valor máximo: {array.max()}")
print(f"Valor médio: {array.mean():.0f}")

Valor minimo: 10
Valor máximo: 77
Valor médio: 36


#### 💎 Podemos fazer operações de matrizes, o que com listas não seria possivel:

In [6]:
a = np.array([1,3])
b = np.array([5,2])

a+b

array([6, 5])

In [7]:
a = np.array([[2,5], [5,6]], dtype=np.int64)
b = np.array([5,2])

a+b

array([[ 7,  7],
       [10,  8]], dtype=int64)

#### 💎 Dimensões (Propriedades):

In [8]:
print(f"Numero de dimensões: {a.ndim}") # usada para determinar o número de dimensões (eixos) de um array.
print(f"Numero de elementos em c/ dim: {a.shape}") # descreve o número de elementos em cada dimensão do array.
print(f"Tipo de dado: {a.dtype}") # Usada para mostrar o tipo de dado.
print(f"Tamanho de cada dado: {a.itemsize}") # determinar o tamanho, em bytes, de cada elemento no array.
print(f"Tamanho total dos dados: {a.nbytes}") # calcular o tamanho total em bytes de um array.

Numero de dimensões: 2
Numero de elementos em c/ dim: (2, 2)
Tipo de dado: int64
Tamanho de cada dado: 8
Tamanho total dos dados: 32


<div style="text-align:center">
    <h3>🎲 Tipos de dados e tamanho ocupados na memória</h3>
    <img src="Datas/dtype.png" width="400rem" />
</div>

#### 💎 Inicializando tipos diferentes de matrizes:

> 👉 As funções np.zeros() e np.ones() são usadas para criar arrays preenchidos com zeros e uns, respectivamente.
> 
> 👉 A função np.full() é usada para criar um array preenchido com um valor específico em todas as suas posições.
>
> 👉 A função fill_value() cria um novo array com a mesma forma do array de entrada, mas preenchido com um valor específice

In [9]:
np.zeros(3) # matriz de uma dimensão 

array([0., 0., 0.])

In [10]:
np.zeros([3, 2], dtype=np.int32) # matriz de duas dimensão, 3 linhas e 2 colunas.

array([[0, 0],
       [0, 0],
       [0, 0]])

In [11]:
np.ones([2, 3, 2]) # 2 matrizes de duas dimensão, cada uma com 3 linhas e 2 colunas.

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [12]:
np.full([3, 4], 21)

array([[21, 21, 21, 21],
       [21, 21, 21, 21],
       [21, 21, 21, 21]])

In [13]:
array = np.array([[2,3], [4,6]])
np.full_like(array, 8) # reutilzia a forma da matriz passada no primeiro aprametro pelo valor do segundo parametro.

array([[8, 8],
       [8, 8]])

<div style="text-align:center">
    <h3>🎲 Outros metodos semelhantes que podem ser úteis</h3>
    <img src="Datas/func1.png" width="400rem" />
</div>

#### 💎 Trabalhando com a geração de números pseudoaleatórios:

In [14]:
np.random.rand(3,3 ) # numeros aleatorios de 0 a 1 

array([[0.5872672 , 0.74831879, 0.02635448],
       [0.37446373, 0.08156679, 0.47092088],
       [0.19935994, 0.44669329, 0.01493404]])

In [15]:
np.random.randn(3, 3) # numeros aleatorios com distribuição normal

array([[ 0.6720898 ,  0.94741531, -1.64552287],
       [-0.31920545,  0.4647081 ,  0.8928589 ],
       [-1.74035669,  0.1503811 ,  1.91200738]])

In [16]:
np.random.randint(1, 67, size=None) # numeros aleatorios dentro desse intervalo
np.random.uniform(4, 9, size=[2,4]) # numeros aleatorios com shape personalizado

array([[8.76583113, 7.96580042, 5.21874933, 5.7385213 ],
       [8.65255384, 7.1708415 , 4.38120385, 5.65658982]])

In [17]:
np.random.normal(loc=5, scale=1) # número aleatório com média 5 e desvio padrão 2

4.305981524685489

In [18]:
myarray = np.array([1,2,3,4,5,6,7])
np.random.shuffle(myarray) # embaralhou o array original, logo mostre o array original.
myarray

array([6, 3, 4, 5, 2, 7, 1])

#### 💎 [CURIOSIDADE] Gerando um DataFrame com numeros aleatorios:

In [19]:
import pandas as pd

In [20]:
shape = [5, 5] # formato da Array
data = np.random.uniform(3, 40, size=shape)

df = pd.DataFrame(data, columns=[f'Coluna {x}' for x in range(5)])

df = df.astype(int)

In [21]:
df

Coluna 0  Coluna 1  Coluna 2  Coluna 3  Coluna 4
0         6        12        39        15        18
1        33        26        33        18        22
2        22        11        23         8        20
3        35         3        15        28        35
4        21        31        12        24        26

#### 💎 Operações de Algebra:

> 👉 identity() usada para criar uma matriz identidade quadrada. Uma matriz identidade é uma matriz quadrada na qual todos os elementos da diagonal principal são iguais a 1 e todos os outros elementos são iguais a 0.
>
> 👉 array.repeat() é usado para repetir elementos de um array ao longo de um ou mais eixos.

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
array = np.array([[1, 2, 3], [3, 4, 5]])
array.repeat(2, axis=1)

array([[1, 1, 2, 2, 3, 3],
       [3, 3, 4, 4, 5, 5]])

#### 💎 Method COPY:

In [24]:
# Modo ERRADO!!!
# Explicação: cópia dependente de a, variável 'b' faz referência à mesma localização de memória que 'a'.

a = np.array([1,2,3])
b = a
b[0] = 10
b

array([10,  2,  3])

In [25]:
# Modo CORRETO!!!
# Explicação: Cria uma cópia independente.

b = a.copy()
b[0] = 4
b

array([4, 2, 3])

#### 💎 Element-wise Operations:

> realização de operações matemáticas em elementos correspondentes de arrays ou vetores.

In [26]:
lista = [1, 2, 6]
# lista + 2 <- Isso vai dar erro! Ok...

In [27]:
numbers1 = np.array([1, 3, 2])
numbers2 = np.array([1, 4, 5])

In [28]:
# Isso vai dar certo... 

print(numbers1 + numbers2)
print(numbers1 - numbers2)
print(numbers1 * numbers2)
print(numbers1 / numbers2)

[2 7 7]
[ 0 -1 -3]
[ 1 12 10]
[1.   0.75 0.4 ]


In [29]:
# Atribuições: 

numbers1 += 4
numbers1

array([5, 7, 6])

In [30]:
a = np.array([1, -3, 2])
b = np.array([1, 4, -5])

In [31]:
a - b

array([ 0, -7,  7])

#### 💎 Reshape:

> A função numpy.reshape é usada para alterar a forma (dimensões) de um array, mantendo os dados no array inalterados.

In [32]:
array = np.array([[1, 1, 6], [3, 5, 6]])
array

array([[1, 1, 6],
       [3, 5, 6]])

In [33]:
array.reshape([3,2])

array([[1, 1],
       [6, 3],
       [5, 6]])

#### 💎 Stacks:

> São funções que permitem empilhar (concatenar) arrays verticalmente (ao longo do eixo das linhas) e horizontalmente (ao longo do eixo das colunas)

In [51]:
a1 = np.array([2, 5, 7])
a2 = np.array([4, 6, 2])

In [52]:
np.vstack([a1, a2, [4, 3, 2]]) # Pilha Vertical

array([[2, 5, 7],
       [4, 6, 2],
       [4, 3, 2]])

In [53]:
np.hstack([a1, [3, 5, 1], a1]) # Pilha Horizontal

array([2, 5, 7, 3, 5, 1, 2, 5, 7])

#### 💎 Mudança de tipo de dado:

> dtype é um atributo dos objetos NumPy que especifica o tipo de dados dos elementos no array.
>
> astype() é um método disponível em objetos NumPy que permite converter o tipo de dados de um array existente

In [54]:
# Antes:

a2.dtype # Verificando o tipo de dado atual

dtype('int32')

In [55]:
# Depois:

a2Float = a2.astype('float32') # Alterando o tipo de dado
a2Float

array([4., 6., 2.], dtype=float32)

#### 💎 CONDICIONAIS //  MASCARAS BOOLEANAS:
> axis=0 (COLUNA) | axis=1 (LINHA)

In [114]:
array = np.random.randint(10, 100, size=[5,5])
array

array([[49, 76, 27, 58, 53],
       [31, 63, 92, 23, 72],
       [99, 64, 36, 23, 36],
       [93, 25, 29, 94, 63],
       [41, 25, 34, 62, 25]])

In [115]:
array[array > 90] # retorna um novo array contendo apenas os elementos do array original

array([92, 99, 93, 94])

In [116]:
np.any(array > 59) # verificar se pelo menos um elemento em um array satisfaz uma determinada condição.

True

In [117]:
np.any(array < 20, axis=0) # Verifica se há pelo menos um valor [que esta de acordo com a condicional] em cada coluna.

array([False, False, False, False, False])

In [118]:
np.any(array < 20, axis=1) # Verifica se há pelo menos um valor [que esta de acordo com a condicional] em cada coluna.

array([False, False, False, False, False])

In [129]:
np.all(array > 1) # verifica se todos os elementos de um array satisfazem uma determinada condição

True

In [134]:
mask = ((array > 24) & (array < 90))
np.all(mask, axis=0)

array([False,  True, False, False,  True])

In [159]:
# Traga pra mim se tem valores que NAO estão dentro dessa intervalo nas coluna 

# True se tem valores fora do intervalo
# True se não tem valores fora do intervalo

mask = ~((array > 30) & (array < 100)) 
np.any(mask, axis=0)

array([False,  True,  True,  True,  True])

In [161]:
# Traga pra mim os valores que NAO estao dentro dessa condição

# True para se não está
# False para se está

~((array > 90) & (array < 100))

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])